//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuThi
    {
        public int MaKhoaThi { get; set; }
        public string CCCD { get; set; }
        public int MaTrinhDo { get; set; }
    
        public virtual KhoaThi KhoaThi { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TrinhDo TrinhDo { get; set; }
    }
}
